Step 1: 웹뷰 생성 구현 완료
yagom-academy/ios-web-browser pull request #4
Opened 2020-11-10 08:35 UTC by hcooch2ch3

### 고민한 점 및 해결 방법

**1. 코드로만 구현하는 방법 VS 스토리보드 병행하여 구현**
코드로만 구현하면 Step 2부터의 구현(뒤로가기, 주소창 등) 또한 다 코드로 구현해서 넣어야 하므로 스토리보드를 병행하여 Step 1을 구현하였습니다.

**2. 스토리보드에서 웹뷰를 배치할 때 상/하단 얼마 간격을 줄 것인가?**
Safe area를 기준으로 상/하단 간격 없이 배치하는 방법 또는 Superview.top/bottom 기준으로 상/하단 간격 없이 배치하는 방법 등을 고민하였으나, 상단은 safe area를 기준으로 하고(Superviw.top으로 설정하면 status bar에 웹페이지가 겹쳐서 보이는 이유 때문에), 하단만 Superview.bottom 기준으로 간격없이 배치하는 걸로 결정하였습니다.

2020-11-10 11:58 UTC, cmindy reviewed
AutoLayout이나 앞으로의 구현(변경사항)을 생각하시는 등 여러가지에 대해 고민을 많이 흔적이 보이네요. 👍
☕  다만, 요구조건은 계속 변경될 수도 있기 때문에 유연하게 대처할 수 있도록 지금 미리 훈련하는 것도 좋은 방법인 것 같습니다.
고생하셨습니다. 아래 comment까지 확인해보세요! 👏 
- google이 아닌 다른 웹사이트에서 bottom에 겹치지는 않을까요? 다음 스텝에서 한 번 더 고민해보세요 🤔 
- 커밋 메세지는 개발 내용을 한 눈에 파악하도록 도와주기 때문에 메세지를 명확하게 작성하고 불필요한 커밋은 하지 않는 것이 좋습니다 :)

2020-11-10 11:58 UTC, cmindy commented on WebBrowser/WebBrowser/ViewController.swift
> +            let urlReq = URLRequest(url: url)
Swift는 약어를 사용하는 것을 지양합니다. 
왜 그런지는 [Swift API Design Guidelines](https://swift.org/documentation/api-design-guidelines/)를 보고 고민해보시면 좋을 것 같습니다.

2020-11-10 11:58 UTC, cmindy commented on WebBrowser/WebBrowser/ViewController.swift
> +        /// 웹뷰에 구글 페이지 로드
코드 내용을 그대로 주석이 설명하고 있다면 주석을 생략할 수 있지 않을까요? 
추가적으로 Swift, Xcode에서 `/// `과 `//`은 약간 쓰임이 다릅니다. 언제 어떤 걸 사용할까요? 🤔

2020-11-10 11:58 UTC, cmindy commented on README.md
> +-test
이 코드를 남겨 놓은 이유가 있을까요 ?

2020-11-10 14:03 UTC, yagom commented
리뷰어의 질문에 대해 의논하고 싶은 부분은 코멘트에서 의논하면 되고, 리뷰 내용을 반영하여 다시 리뷰를 받고 싶은 경우에는 리뷰어를 태그하여 코멘트 하면 됩니다. 
그리고 깃헙 프로필 사진을 등록해두면 누가 커밋했는지 로그를 볼 때 훨씬 편할것 같아요 :) 얼굴이 아니더라도 구분할 수 있는 프로필 이미지를 등록하는게 어떨까요?
@hcooch2ch3 @soleJin @cmindy

2020-11-11 14:31 UTC, hcooch2ch3 commented on README.md
> +-test
잘못 추가된 내용입니다.. 다음 스텝에 삭제할게요.

2020-11-11 14:36 UTC, hcooch2ch3 commented on WebBrowser/WebBrowser/ViewController.swift
> +        /// 웹뷰에 구글 페이지 로드
///은 Documentation 주석을 추가할때 사용하고, //은 Non-Documentation 주석을 추가할때 사용한다고 알고 있습니다.

2020-11-11 15:23 UTC, hcooch2ch3 commented
@cmindy @yagom 리뷰해주신 내용 (변수명에 포함된 약어 수정, 필요 없는 주석 삭제, README.md에 잘못들어간 내용 삭제) 반영하고 Step2 구현하여 커밋하였습니다. 머지 요청드립니다!

2020-11-12 00:24 UTC, yagom commented on WebBrowser/WebBrowser/ViewController.swift
> +        /// 웹뷰에 구글 페이지 로드
그렇다면 ///는 정의부에 사용하는 것이 맞지 않을까요?

2020-11-12 00:27 UTC, yagom commented
스텝 1 PR에 스텝 2 내용까지 함께 보냈네요~
다음 부터는 스텝 1 리뷰 및 머지가 완료된 후에 스텝 2 PR은 따로 만들어 보내주세요~
@cmindy 스텝2까지 한방에 부탁해요~

2020-11-12 03:07 UTC, yagom requested changes
깔끔하게 잘 구현하고 있습니다 :)
확인해봐야할 오타가 있어요~

2020-11-12 03:07 UTC, yagom commented on WebBrowser/WebBrowser/ViewController.swift
> +    @IBOutlet weak var addressTextField: UITextField!
주소는 주소인데 어떤 주소일까요?

2020-11-12 03:07 UTC, yagom commented on WebBrowser/WebBrowser/ViewController.swift
> +    /// - Parameter of: 이동할 웹페이지의 주소 문자열.
문서화 주석은 좋습니다!

2020-11-12 03:07 UTC, yagom commented on WebBrowser/WebBrowser/ViewController.swift
> +    /// - Parameter of: 이동할 웹페이지의 주소 문자열.
loadWebPage(of:) 메서드를 호출하는 부분에서 옵션키를 누르고 메서드를 클릭하면 제대로 퀵헬프가 표시되나요?

2020-11-12 03:07 UTC, yagom commented on WebBrowser/WebBrowser/ViewController.swift
> +    @IBAction func touchUpGoBarButtonItme(_ sender: UIBarButtonItem) {
복붙은 항상 조심해야겠죠? 아래에도 확인해보세요 :)

2020-11-12 03:07 UTC, yagom commented on WebBrowser/WebBrowser/ViewController.swift
> +        mainWebView.goBack()
웹 페이지가 뒤로 가지 못하거나 앞으로 가지 못하는 상황이 있을수도 있겠죠? 어떻게 하면 사용자에게 직관적으로 표현해줄 수 있을까요?

2020-11-12 03:07 UTC, yagom commented on WebBrowser/WebBrowser/ViewController.swift
> +        mainWebView.goBack()
이건 질문예요. 묵시적 요구조건이라고 볼 수도 있어요. 하지만 지금 당장 퍼뜩 떠오르지 않거나 방법을 찾는데 한 시간 이상 소요하게 된다면 넘어갑시다.

2020-11-12 06:07 UTC, cmindy reviewed
고생하셨습니다~ 코멘트 남겨놓았으니 확인하시고 함께 얘기해봐요!! 🤗

2020-11-12 06:07 UTC, cmindy commented on WebBrowser/WebBrowser/ViewController.swift
> +            loadWebPage(of: address)
여기서는 self를 사용하지 않으셨군요ㅎㅎ! 사용하지 않은 의도가 있으실까요~?

2020-11-12 06:07 UTC, cmindy commented on WebBrowser/WebBrowser/ViewController.swift
> +    @IBOutlet weak var addressTextField: UITextField!
어떤 component인지 변수명만 보고도 바로 알 수 있어서 좋네요👍

2020-11-12 06:07 UTC, cmindy commented on WebBrowser/WebBrowser/ViewController.swift
> +    @IBOutlet weak var backBarButtonItem: UIBarButtonItem!
사용하지 않는 아울렛 변수들을 남겨놓으신 이유가 있을까요?

2020-11-12 06:07 UTC, cmindy commented on WebBrowser/WebBrowser/ViewController.swift
> +    @IBOutlet weak var mainWebView: WKWebView!
접근 제한자에 대해 알아보시고 적용해주셔도 좋을 것 같습니다!🤗

2020-11-12 08:03 UTC, hcooch2ch3 commented on WebBrowser/WebBrowser/ViewController.swift
> +    /// - Parameter of: 이동할 웹페이지의 주소 문자열.
@yagom @cmindy @soleJin 넵 옵션키 눌렀을때 퀵헬프 잘 나옵니다. 주석 작성하면 이런 기능이 되는지 몰랐는데, 유용하게 사용하겠습니다!

2020-11-12 08:04 UTC, hcooch2ch3 commented on WebBrowser/WebBrowser/ViewController.swift
> +    @IBOutlet weak var addressTextField: UITextField!
@yagom @cmindy @soleJin 로드할 페이지 주소입니다.

2020-11-12 08:05 UTC, hcooch2ch3 commented on WebBrowser/WebBrowser/ViewController.swift
> +            loadWebPage(of: address)
@yagom @cmindy @soleJin 아뇨 실수로 빠뜨렸습니다..

2020-11-12 08:40 UTC, hcooch2ch3 commented on WebBrowser/WebBrowser/ViewController.swift
> +    @IBOutlet weak var backBarButtonItem: UIBarButtonItem!
@yagom @cmindy @soleJin 아뇨.. 현재 커밋에서는 필요없는 변수인데 실수로 안지웠습니다..ㅠㅠ

2020-11-12 09:32 UTC, hcooch2ch3 commented
@cmindy @yagom 코멘트 해주신 내용 반영해서 Step 2 커밋 다시 올렸습니다. 머지 부탁드립니다!

2020-11-12 12:29 UTC, yagom approved these changes
좋아요! 다음 스텝으로 넘어가 봅시다.
코멘트는 확인해보세요~

2020-11-12 12:29 UTC, yagom commented on WebBrowser/WebBrowser/ViewController.swift
> +        self.mainWebView.goBack()
self를 사용할 때와 사용하지 않을때의 차이점이 있나요? 어떤 차이가 있니요?

2020-11-12 12:29 UTC, merged

2020-11-12 15:03 UTC, hcooch2ch3 commented on WebBrowser/WebBrowser/ViewController.swift
> +        self.mainWebView.goBack()
@soleJin self를 사용하면 뷰컨트롤러의 프로퍼티라는 의미가 더 명확해지는 것 같습니다.