웹 브라우저 - Step 1 웹 뷰 생성
yagom-academy/ios-web-browser pull request #5
Opened 2020-11-10 09:01 UTC by zdodev

- 앱 실행 시 전체화면에 웹페이지를 출력하도록 구현하였습니다.
- WKWebView(WebKit View)를 사용하였습니다.

2020-11-10 14:51 UTC, yagom approved these changes
좋습니다!
코드 자체로는 문제 없으니 다음 스텝으로 넘어갑시다. 
코멘트에 있는 질문은 한 번 생각해보세요~

2020-11-10 14:51 UTC, yagom commented on README.md
> +### 웹 브라우저 프로젝트 - Step 1
ㅎㅎ README 파일을 저장소 설명 파일입니다. 이 브랜치는 STEP1 브랜치겠지만, 머지하면 저장소 전체를 대표하는 얼굴의 README가 되지 않을까요?

2020-11-10 14:51 UTC, yagom commented on WebBrowser/WebBrowser/ViewController.swift
> +    @IBOutlet weak var webView: WKWebView!
`weak`를 사용한 이유는 뭘까요?

2020-11-10 14:51 UTC, yagom commented on WebBrowser/WebBrowser/ViewController.swift
> -        // Do any additional setup after loading the view.
필요없는 코드를 정리해서 좋네요 :)

2020-11-10 14:51 UTC, yagom commented on WebBrowser/WebBrowser/ViewController.swift
> +        loadWebPage(url: "https://www.rapid7.com")
ㅎㅎ 이 웹사이트 좋아하는 사이트예요?

2020-11-10 14:51 UTC, yagom commented on WebBrowser/WebBrowser/ViewController.swift
> +        if let requestUrl = URL(string: url) {
만약 if let 구문 내부로 들어가지 못하면 어떻게 될까요? 사용자에게 적절한 피드백을 줘도 좋겠네요 :)

2020-11-10 14:51 UTC, yagom commented
수정하고 싶은 내용이 있으면 수정하여 커밋하고, 그렇지 않으면 머지요청 해주세요.

2020-11-11 07:11 UTC, yagom requested changes
기존의 코멘트 질문에 대해선 아직 고민중인가요?
프로젝트 요구사항은 공개 저장소에 작성할 수 없습니다

2020-11-11 07:11 UTC, yagom commented on WebBrowser/WebBrowser/ViewController.swift
> +    func showInvaildUrlAlert() {
😄

2020-11-11 07:11 UTC, yagom commented on README.md
> +- 웹 뷰에서 즐겨찾는 웹 페이지 불러오도록 기능 구현
프로젝트 요구조건은 적지 말아주세요~
요거 빼주면 머지할게요

2020-11-11 08:34 UTC, zdodev commented on WebBrowser/WebBrowser/ViewController.swift
> +    @IBOutlet weak var webView: WKWebView!
swift의 메모리 관리 기법 중 strong과 weak이 있습니다. strong은 강한 참조, weak은 약한 참조라 부릅니다. strong의 경우 객체를 참조할 때마다 레퍼런스 카운트를 증가시켜 strong으로 참조한 후 뷰를 제거했을 때 메모리에서 제거되지 않는 문제점이 있다고 합니다. 그래서 strong은 뷰를 씬에서 지웠다가 다시 추가해야 할 때 사용하고 그럴 필요가 없다면 기본적으로 weak을 사용한다고 하여 weak을 사용하였습니다.

2020-11-11 15:22 UTC, merged